#### Plugin Configuration
## Jacob Tyo
## 12/08/2011
#### Permissions:
## battlezones.help
## battlezones.add
## battlezones.remove
## battlezones.enable
## battlezones.disable
## battlezones.list
## battlezones.pvp
---
name: BattleZones
main: js2.battlezones.BattleZones
version: 0.0.00 [1566]
commands:
   bz:
      description: Print help info for BattleZones.
      permission: battlezones
      usage: /bz