## Plugin Configuration
## Jacob Tyo
## 12/10/2011
---
name: BattleZones
main: js2.battlezones.BattleZones
version: 0.0.10 [1566]
commands:
   bz:
      description: Print help info for BattleZones.
      permission: battlezones.bz
      usage: /bz